# Site settings
author: Solomon R Feldman
title: Solomon R Feldman
header-img: img/home-bg.png
email: solomonrfeldman@gmail.com
copyright_name: Solomon R Feldman
description: > # this means to ignore newlines until "baseurl:"
  Student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SolomonRFeldman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
